name: Check Appointments

on:
  schedule:
    - cron: '0 7-23 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      API_URL: ${{ secrets.API_URL }}
      EMAIL_URL: ${{ secrets.EMAIL_URL }}
      EMAIL_API_KEY: ${{ secrets.EMAIL_API_KEY }}
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
      EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python check_appointments.py

      - name: Check for changes
        id: git-check
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            git commit -m "Update date file [auto]"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Push changes
        if: steps.git-check.outputs.changed == 'true'
        run: git push


